spring.application.name=megabackend
# MongoDB Atlas Connection
spring.data.mongodb.uri=mongodb+srv://dbadmin:Moncsk12ad@cluster0.ll5kk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=megacitycab
